-- Add unique human-readable campaign_id for reference and filtering
-- Format: CMP-CLIENTNAME-CAMPAIGNNAME-YYYY-MMDD-XXXX (generated by app on create)

-- Add column (nullable first for backfill)
ALTER TABLE public.campaigns
  ADD COLUMN IF NOT EXISTS campaign_id text;

-- Backfill existing rows in short format: CMP-CLIENTNAME-CAMPAIGNNAME-YYYY-MMDD-XXXX
-- Uses client_name, name, created_at; 4-char suffix from MD5(id) for uniqueness
UPDATE public.campaigns
SET campaign_id =
  'CMP-'
  || CASE WHEN LENGTH(TRIM(UPPER(REGEXP_REPLACE(COALESCE(client_name, 'LEGACY'), '[^A-Za-z0-9]', '', 'gi')))) > 0
     THEN SUBSTRING(TRIM(UPPER(REGEXP_REPLACE(COALESCE(client_name, 'LEGACY'), '[^A-Za-z0-9]', '', 'gi'))), 1, 24)
     ELSE 'LEGACY' END
  || '-'
  || CASE WHEN LENGTH(TRIM(UPPER(REGEXP_REPLACE(COALESCE(name, 'CAMPAIGN'), '[^A-Za-z0-9]', '', 'gi')))) > 0
     THEN SUBSTRING(TRIM(UPPER(REGEXP_REPLACE(COALESCE(name, 'CAMPAIGN'), '[^A-Za-z0-9]', '', 'gi'))), 1, 24)
     ELSE 'CAMPAIGN' END
  || '-'
  || TO_CHAR(created_at, 'YYYY')
  || '-'
  || TO_CHAR(created_at, 'MMDD')
  || '-'
  || UPPER(SUBSTRING(MD5(id::text), 1, 4))
WHERE campaign_id IS NULL;

-- Enforce NOT NULL (after backfill)
ALTER TABLE public.campaigns
  ALTER COLUMN campaign_id SET NOT NULL;

-- UNIQUE constraint (no duplicate campaign_id allowed) — idempotent
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'campaigns_campaign_id_unique'
    AND conrelid = 'public.campaigns'::regclass
  ) THEN
    ALTER TABLE public.campaigns
      ADD CONSTRAINT campaigns_campaign_id_unique UNIQUE (campaign_id);
  END IF;
END $$;

-- Index for filtering (unique constraint already creates an index; optional explicit name)
CREATE INDEX IF NOT EXISTS idx_campaigns_campaign_id
  ON public.campaigns (campaign_id);
