/**
 * Enum options for the lead engine's input fields — extracted from the
 * actor's input schema (2026-07). UI selects and JSON-mode validation both
 * use these so invalid values never reach the engine.
 */

export const SENIORITY_OPTIONS: { value: string; label: string }[] = [
  { value: "founder", label: "Founder" },
  { value: "owner", label: "Owner" },
  { value: "c_suite", label: "Executive (C-Suite)" },
  { value: "director", label: "Director" },
  { value: "partner", label: "Partner" },
  { value: "vp", label: "Vice President" },
  { value: "head", label: "Head" },
  { value: "manager", label: "Manager" },
  { value: "senior", label: "Senior" },
  { value: "entry", label: "Entry Level" },
  { value: "trainee", label: "Trainee" },
];

export const FUNCTIONAL_OPTIONS: { value: string; label: string }[] = [
  { value: "c_suite", label: "C-Suite" },
  { value: "finance", label: "Finance" },
  { value: "product_management", label: "Product Management" },
  { value: "engineering", label: "Engineering" },
  { value: "design", label: "Design" },
  { value: "education", label: "Education" },
  { value: "human_resources", label: "Human Resources" },
  { value: "information_technology", label: "Information Technology" },
  { value: "legal", label: "Legal" },
  { value: "marketing", label: "Marketing" },
  { value: "operations", label: "Operations" },
  { value: "sales", label: "Sales" },
  { value: "support", label: "Support" },
];

export const EMAIL_STATUS_SELECT_OPTIONS: { value: string; label: string }[] = [
  { value: "validated", label: "Validated" },
  { value: "not_validated", label: "Not Validated" },
  { value: "unknown", label: "Unknown" },
];

export const COMPANY_SIZE_SELECT_OPTIONS = [
  "1-10",
  "11-20",
  "21-50",
  "51-100",
  "101-200",
  "201-500",
  "501-1000",
  "1001-2000",
  "2001-5000",
  "5001-10000",
  "10001-20000",
  "20001-50000",
  "50000+",
] as const;

export const REVENUE_OPTIONS = [
  "100K",
  "500K",
  "1M",
  "5M",
  "10M",
  "25M",
  "50M",
  "100M",
  "500M",
  "1B",
  "5B",
  "10B",
] as const;

export const FUNDING_OPTIONS: { value: string; label: string }[] = [
  { value: "seed", label: "Seed Round" },
  { value: "angel", label: "Angel Round" },
  { value: "series_a", label: "Series A" },
  { value: "series_b", label: "Series B" },
  { value: "series_c", label: "Series C" },
  { value: "series_d", label: "Series D" },
  { value: "series_e", label: "Series E" },
  { value: "series_f", label: "Series F" },
  { value: "venture_round", label: "Venture Round" },
  { value: "debt_financing", label: "Debt Financing" },
  { value: "convertible_note", label: "Convertible Note" },
  { value: "private_equity_round", label: "Private Equity Round" },
  { value: "other_round", label: "Other Round" },
];

export const LOCATION_OPTIONS = [
  "united states",
  "germany",
  "india",
  "united kingdom",
  "russia",
  "france",
  "china",
  "canada",
  "netherlands",
  "mexico",
  "belgium",
  "japan",
  "brazil",
  "australia",
  "poland",
  "thailand",
  "sweden",
  "portugal",
  "spain",
  "czech republic",
  "taiwan",
  "south africa",
  "colombia",
  "italy",
  "vietnam",
  "nigeria",
  "singapore",
  "hong kong",
  "ireland",
  "israel",
  "switzerland",
  "turkey",
  "romania",
  "south korea",
  "indonesia",
  "united arab emirates",
  "saudi arabia",
  "austria",
  "philippines",
  "peru",
  "malaysia",
  "argentina",
  "ukraine",
  "ghana",
  "denmark",
  "norway",
  "finland",
  "puerto rico",
  "qatar",
  "macau",
  "new zealand",
  "hungary",
  "luxembourg",
  "kuwait",
  "egypt",
  "slovakia",
  "greece",
  "kenya",
  "bulgaria",
  "costa rica",
  "chile",
  "venezuela",
  "afghanistan",
  "bangladesh",
  "malta",
  "guatemala",
  "pakistan",
  "lithuania",
  "panama",
  "morocco",
  "republic of indonesia",
  "uruguay",
  "serbia",
  "bolivia",
  "angola",
  "dominican republic",
  "ecuador",
  "oman",
  "jamaica",
  "zambia",
  "lebanon",
  "tanzania",
  "jordan",
  "algeria",
  "gibraltar",
  "paraguay",
  "cambodia",
  "uganda",
  "mozambique",
  "ethiopia",
  "belarus",
  "republic of the union of myanmar",
  "croatia",
  "jersey",
  "iraq",
  "isle of man",
  "el salvador",
  "estonia",
  "latvia",
  "côte d'ivoire",
  "tunisia",
  "sierra leone",
  "senegal",
  "sri lanka",
  "cyprus",
  "kazakhstan",
  "guernsey",
  "bermuda",
  "mali",
  "honduras",
  "bahrain",
  "slovenia",
  "papua new guinea",
  "iceland",
  "mauritius",
  "iran",
  "niger",
  "rwanda",
  "moldova",
  "democratic republic of the congo",
  "liechtenstein",
  "fiji",
  "kyrgyzstan",
  "azerbaijan",
  "madagascar",
  "trinidad and tobago",
  "lesotho",
  "nicaragua",
  "cameroon",
  "barbados",
  "armenia",
  "haiti",
  "maldives",
  "guam",
  "laos",
  "nepal",
  "brunei",
  "reunion",
  "macedonia (fyrom)",
  "swaziland",
  "liberia",
  "uzbekistan",
  "sudan",
  "anguilla",
  "cuba",
  "cayman islands",
  "seychelles",
  "saint kitts and nevis",
  "suriname",
  "bosnia and herzegovina",
  "malawi",
  "the bahamas",
  "botswana",
  "syria",
  "burundi",
  "guadeloupe",
  "namibia",
  "burkina faso",
  "somalia",
  "greenland",
  "equatorial guinea",
  "chad",
  "monaco",
  "republic of the congo",
  "u.s. virgin islands",
  "mayotte",
  "french polynesia",
  "french guiana",
  "andorra",
  "new caledonia",
  "central african republic",
  "myanmar (burma)",
  "belize",
  "aland islands",
  "solomon islands",
  "kosovo",
  "gabon",
  "benin",
  "bonaire, sint eustatius and saba",
  "martinique",
  "tonga",
  "south sudan",
  "cook islands",
  "georgia",
  "mauritania",
  "turkmenistan",
  "libya",
  "falkland islands (islas malvinas)",
  "bhutan",
  "tajikistan",
  "northern mariana islands",
  "western sahara",
  "guyana",
  "dominica",
  "vanuatu",
  "kiribati",
  "togo",
  "nauru",
  "samoa",
  "mongolia",
  "myanmar",
  "yemen",
  "albania",
  "montenegro",
  "california, us",
  "texas, us",
  "england, united kingdom",
  "new york, us",
  "florida, us",
  "illinois, us",
  "moscow, russia",
  "bavaria, germany",
  "pennsylvania, us",
  "virginia, us",
  "ohio, us",
] as const;

export const SENIORITY_SET = new Set(SENIORITY_OPTIONS.map((o) => o.value));
export const FUNCTIONAL_SET = new Set(FUNCTIONAL_OPTIONS.map((o) => o.value));
export const EMAIL_STATUS_SET = new Set(EMAIL_STATUS_SELECT_OPTIONS.map((o) => o.value));
export const COMPANY_SIZE_SET = new Set<string>(COMPANY_SIZE_SELECT_OPTIONS);
export const REVENUE_SET = new Set<string>(REVENUE_OPTIONS);
export const FUNDING_SET = new Set(FUNDING_OPTIONS.map((o) => o.value));
export const LOCATION_SET = new Set<string>(LOCATION_OPTIONS);
